# Generated by Django 4.2.7 on 2025-02-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='transfer_code_required',
            field=models.BooleanField(default=True, help_text='If enabled, requires transfer code for withdrawals'),
        ),
        migrations.AlterField(
            model_name='user',
            name='transfer_code',
            field=models.CharField(blank=True, default='00075', max_length=30, null=True),
        ),
    ]
