# Generated by Django 4.2.7 on 2025-02-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_transfer_code_required_alter_user_transfer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_block',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='change_mail',
            field=models.BooleanField(default=False),
        ),
    ]
